name: Bug report (1.x)
description: Шаблон ошибок в Vue Yandex Maps 1.x
labels: ["bug", "1.x"]
assignees:
  - PNKBizz
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время указать нам на наши ошибки!
  - type: input
    id: version
    attributes:
      label: Версия библиотеки
      description: Пожалуйста, укажите версию библиотеки на момент написания этой формы
      placeholder: Например, 1.0.0
    validations:
      required: true
  - type: textarea
    id: how-to
    attributes:
      label: Как воспроизвести
      description: Опишите здесь шаги воспроизведения, приведите примеры кода, а еще лучше - укажите репозиторий, где можно воспроизвести проблему.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Опишите проблему
      description: Опишите простым и понятным языком, что идет не так.
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Как должно быть
      description: Расскажите, какой ожидаемый результат вы хотели бы видеть.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Дополнительная информация
      description: Опишите, что еще нам нужно знать.
    validations:
      required: false
  - type: checkboxes
    id: validation
    attributes:
      label: Немного формальностей
      description: Пожалуйста, сверьтесь с пунктами ниже
      options:
        - label: Я использую версию 1.x
          required: true
        - label: Я поискал похожие ошибки и не нашел таковых
          required: true
