blank_issues_enabled: false
contact_links:
  - name: 📚 Документация версии 1.х
    url: https://vue-yandex-maps.github.io/new-docs/
    about: Сверьтесь с документацией по первой версии пакета
  - name: 📚 Документация версии 2.х
    url: https://yandex-maps-unofficial.github.io/vue-yandex-maps/
    about: Сверьтесь с документацией по второй версии пакета
  - name: 💬 Дискуссии
    url: https://github.com/yandex-maps-unofficial/vue-yandex-maps/discussions
    about: Если у вас есть вопрос по использованию проекта или вы не уверены, что всё делаете правильно - загляните в наш раздел Дискуссий.
