name: Code check V2

on:
  pull_request:
    branches: [ v2 ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - uses: ./.github/actions/codecheck
